pages:
 image: node:latest
 stage: deploy
 environment: production
 script:
  - npm install --progress=false
  - npm run prod
  - rm -rf public
  - mkdir public
  - cp -r dist/* public/
 artifacts:
  expire_in: 1 day
  paths:
  - public
 only:
  - main